services:
  setup:
    image: alpine
    volumes:
      - ./scripts/mediawiki-entrypoint.sh:/scripts/setup.sh:ro
      - ./data:/data:ro
      - ./extensions:/extensions:ro
    command: [ "/bin/sh", "/scripts/setup.sh" ]
    depends_on:
      database:
        condition: service_healthy

  mediawiki:
    image: mediawiki:${MW_VERSION:-latest}
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./data:/var/www/data:ro
      - ./extensions:/var/www/html/extensions:ro
      - mediawiki_data:/var/www/html/images
    environment:
      - MW_DB_HOST=database
      - MW_DB_USER=wikiuser
      - MW_DB_PASS=wikipass
      - MW_DB_NAME=my_wiki
    depends_on:
      setup:
        condition: service_completed_successfully
      database:
        condition: service_healthy

  database:
    image: mariadb:11
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=my_wiki
      - MYSQL_USER=wikiuser
      - MYSQL_PASSWORD=wikipass
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
  mediawiki_data:
